api-token/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :works
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    resources :works
  end

end

api-token/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

api-token/app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :jwt_authenticatable, jwt_revocation_strategy: self

  def jwt_payload
    super.merge({ email: email })
  end

end

api-token/app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  validates :title, :description, :user, presence: true

end

api-token/app/controllers/api/works_controller.rb
module Api
  class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
    render json: @works
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)
    if @work.save
      render :show, status: :created, location: @work, format: :json
    else
      render json: @work.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    if @work.update(work_params)
      render :show, status: :ok, location: @work
    else
      render json: @work.errors, status: :unprocessable_entity
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:title, :description, :user_id)
    end
end

end

api-token/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
  respond_to :json
end

api-token/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:title, :description, :user_id)
    end
end

api-token/app/helpers/api/works_helper.rb
module Api::WorksHelper
end

api-token/app/helpers/application_helper.rb
module ApplicationHelper
end

api-token/app/helpers/works_helper.rb
module WorksHelper
end

api-token/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

api-token/app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

api-token/app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

api-token/app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.title %></td>
        <td><%= work.description %></td>
        <td><%= work.user %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

api-token/app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

api-token/app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @work.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @work.user %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>